### ISSUE TITLE
Disqus comments

### ISSUE THREAD

**Issue by danimesq** [ZeroCoinOrganization/ZeroCoinOrganization.github.io#1]

**Comment by purplesyringa** [comment]
No Disqus, please. It includes *a lot* of analytics, really **A LOT**. We should either make our own comment system (which sounds difficult on GitHub pages) or use something else.

**Comment by danimesq** [comment]
@imachug
I draw on paper a comment system exclusive for ZeroNet, called Qomments.
Please tell me if you is interested.

**Comment by purplesyringa** [comment]
I defenitely am.

**Comment by danimesq** [comment]
@imachug
Can I create a repo?
Or youself can create your repo without me as admin.
